name: epm_order_desk
description: EPM ORDER DESK — Internal Sales Management App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  http_parser: ^4.0.2
  shared_preferences: ^2.2.3
  file_picker: ^8.0.0
  excel: ^4.0.0
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/invent.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/invent.png"
flutter:
  uses-material-design: true
  assets:
    - assets/invent.png